language: python
services:
- docker
python:
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
deploy:
  - provider: heroku
  - app: shielded-shelf-72212
  - api_key: ${HEROKU_API_KEY}
